<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfImage extends BasesfImage
{
  public function setReference($reference) {
    $reference = preg_replace(array('/\//', '/ /'), '_', $reference);
    return $this->_set('reference', $reference);
  }

  public function setMimeType($mimeType) {
    if(!$this->_get('extension')) {
      switch($mimeType) {
        case 'image/bmp':
          $this->_set('extension', 'bmp');
          break;
        case 'image/gif':
          $this->_set('extension', 'gif');
          break;
        case 'image/x-icon':
          $this->_set('extension', 'ico');
          break;
        case 'image/jpeg':
        case 'image/pjpeg':
          $this->_set('extension', 'jpg');
          break;
        case 'image/png':
          $this->_set('extension', 'png');
          break;
        case 'image/tiff':
        case 'image/x-tiff':
          $this->_set('extension', 'tif');
          break;
      }
    }

    return $this->_set('mime_type', $mimeType);
  }

  public function getLastModified() {
    return date('r',time($this->_get('last_modified')));
  }

  public function getUrl() {
    sfLoader::loadHelpers('Url');
    return url_for('sfImages/show?reference='.$this->_get('reference').'&extension='.$this->_get('extension'));
  }
}