<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfImageTable extends Doctrine_Table
{
  public static function newImage($name, $fileDescr) {
    $image = new sfImage();
    $image->setReference($name);


    if(!($fileDescr instanceof sfValidatedFile)) {
      if(is_array($fileDescr)) {
        $fileDescr = new sfValidatedFile($fileDescr['name'], $fileDescr['type'], $fileDescr['tmp_name'], $fileDescr['size']);
      }
      else {
        throw new sfException('File description not supported, use sfValidatedFile or array');
      }
    }

    $file = fopen($fileDescr->getTempName(), 'r');
    $image->setContent(fread($file, $fileDescr->getSize()));
    fclose($file);

    $image->setSize($fileDescr->getSize());
    $image->setMimeType($fileDescr->getType());
    $image->setLastModified(date('Y-m-d H:i:s'));

    $image->save();
    return $image;
  }
}